const SENSOR_TYPE = {
    TEMPERATURE_HUMIDITY: 'TEMPERATURE_HUMIDITY',
    INFRARED: 'INFRARED',
    POSITION: 'POSITION',
    IMAGE: 'IMAGE',
    RADIATION: 'RADIATION',
}

module.exports = {
    SENSOR_TYPE
}